--新增用户详情
SELECT CONVERT(char(10), OPERATE_TIME, 120) as '日期',CUSTOMER_NAME as '姓名',CUSTOMER_TYPE as '用户类型',CUSTOMER_PHONE as '注册电话'
FROM bs07.dbo.C_CUSTOMER_INFORMATION
where OPERATE_TIME BETWEEN '2016/10/1' and '2016/10/31' 
--昨日新增用户
SELECT COUNT(DISTINCT(CUSTOMER_ID)) as '昨日注册用户数'from bs07.dbo.C_CUSTOMER_INFORMATION 
WHERE OPERATE_TIME BETWEEN '2016/10/24' and '2016/10/25' 
--昨日租赁用户数（已付款）
SELECT COUNT(DISTINCT(CUSTOMER_ID)) as '昨日租赁用户数' from bs07.dbo.R_RV_BOOK_INFORMATION 
where STATE > 3 and STATE <> 9 and RENT_START_TIME BETWEEN '2016/10/24' and '2016/10/25' 
--
SELECT CONVERT(char(10), SETTLEMENT_DATE, 120) as '日期', BOOK_RV_NO as '订单号',CUSTOMER_NAME as '用户姓名',AC_RV_RENT_MONEY as '实际租金', MAINTENANCE_COSTS as '维养费用',
AC_DRIVE_RV_MONEY as '代驾费用',AC_SEND_RV_MONEY as '还车节假日费用',AC_TAKE_RV_MONEY as '取车节假日费用',AC_SERVICE_FEE as '服务费',
AC_GOODS_RENT_MONEY as '租赁物品费用',AC_GOODS_SALE_MONEY as '购买物品费用',AC_OTHER_REVENUE_MONEY as '其他收入',
AC_DISCOUNT_MONEY as '折扣金' from bs07.dbo.F_SETTLEMENT_MANAGEMENT
where SETTLEMENT_DATE BETWEEN '2016/10/1' and '2016/10/31' 
ORDER BY CONVERT(char(10), SETTLEMENT_DATE, 120)